<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ding_mobile_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
  elseif ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}
/**
 * Implementation of hook_menu().
 */
function ding_mobile_menu(){
  $items = array();
    
  $items['user/status'] = array(
    'title' => 'user status',
    'page callback' => 'ding_mobile_forward_to_status',
    'access callback' => true,
  );
  return $items;
}
/*
 * page callback to forward to user loanstatus
 */
function ding_mobile_forward_to_status(){
  global $user;
  if($user->uid){
    drupal_goto('user/'.$user->uid.'/status');
  }
  else{
    drupal_goto('user/login','destination=user/status');
  }
}


function ding_mobile_preprocess_ting_search_collection(&$variables){
  if ($variables['collection']->objects[0] instanceOf TingClientObject) {
    $image_url = ting_covers_collection_url($variables['collection']->objects[0], '80_x');
    if ($image_url) {
      #$variables['picture'] = theme('image', $image_url, '', '', null, false);
    }
  }
}


/**
 * Override normal ting_search_form
 */
function ding_mobile_form_ting_search_form_alter(&$form,&$form_state) {
  
  $form['keys']['#title'] = t('searchphrase');
  //unset($form['example_text']);
  //$form['example_text']['#value'] = l(t('Search help'),'node/5');
  $form['submit']['#type'] = 'image_button';
  $form['submit']['#src'] = drupal_get_path('theme','mkolding').'/images/search-btn.png'; 
  
  return $form;
}


function ding_mobile_form_ding_reservation_confirm_form_alter(&$form,&$form_state){
  
  #var_dump($form['object']['#value']->title);
  $title = $form['object']['#value']->title;
  $form['description']['#value'] = '<h1>'.t('confirm reservation').'</h1><p>'.t('You are about to book %material. Are you sure you want to continue?',array('%material' => $title)).'</p>';
  
  return $form;
}

/**
 * Implementation of hook_ting_object_buttons().
 */
function ding_mobile_ting_object_buttons($object) {
  if (!empty($object->localId) && ting_object_is($object, 'reservable')) {
    return '<button onclick="location.href=\''.url('ding/reservation/' . $object->localId,array('query' => drupal_get_destination(),'absolute' => true)).'\';">'.t('Reserve now').'</button>';
  }
}


/**
 * migrating all list images to list image mobile
 */
function ding_mobile_update_6001(){

  $result = db_query('select nid from node');
  while($row = db_fetch_array($result)){
    $n = node_load($row['nid']);
    if($n->type == 'article' OR $n->type == 'event'){
      if($n->field_list_image_mobile[0] == null AND $n->field_list_image[0] != null){
        $n->field_list_image_mobile = $n->field_list_image;
        node_save($n);
        //dsm($n);
      }
    }
  }
}