<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ding_mobile_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
  elseif ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}
/**
 * Implementation of hook_menu().
 */
function ding_mobile_menu(){
  $items = array();
    
  $items['user/status'] = array(
    'title' => 'user status',
    'page callback' => 'ding_mobile_forward_to_status',
    'access callback' => true,
  );
  return $items;
}
/*
 * page callback to forward to user loanstatus
 */
function ding_mobile_forward_to_status(){
  global $user;
  #print 'user/'.$user->uid.'/status';
  #return;
  drupal_goto('user/'.$user->uid.'/status');
}


function ding_mobile_preprocess_ting_search_collection(&$variables){
  if ($variables['collection']->objects[0] instanceOf TingClientObject) {
    $image_url = ting_covers_collection_url($variables['collection']->objects[0], '80_x');
    if ($image_url) {
      #$variables['picture'] = theme('image', $image_url, '', '', null, false);
    }
  }
}


/**
 * Override normal ting_search_form
 */
function ding_mobile_form_ting_search_form_alter(&$form,&$form_state) {
  
  $form['keys']['#title'] = t('searchphrase');
  //unset($form['example_text']);
  $form['example_text']['#value'] = l(t('Search help'),'/ting/search/help');
  $form['submit']['#type'] = 'image_button';
  $form['submit']['#src'] = drupal_get_path('theme','mkolding').'/images/search-btn.png'; 
  
  return $form;
}