<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ding_mobile_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
  elseif ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}


/**
 * Override normal ting_search_form
 */
function ding_mobile_form_ting_search_form_alter(&$form,&$form_state) {
  
  $form['keys']['#title'] = t('searchphrase');
  //unset($form['example_text']);
  $form['example_text']['#value'] = l(t('Search help'),'/ting/search/help');
  $form['submit']['#type'] = 'image_button';
  $form['submit']['#src'] = drupal_get_path('theme','mkolding').'/images/search-btn.png'; 
  
  return $form;
}